### ISSUE TITLE
5주차: 5장 웹서버 & 6장 프록시 

### ISSUE THREAD

**Issue by SeolYoungKim** [SeolYoungKim/http-definitive-guide-study#18]
## 05장 웹서버 & 06장 프록시 
- 질문 혹은 토론거리를 댓글로 달아주세요.
- 하나의 댓글에 두 컨텐츠를 모두 넣어주세요.
- 자기 자신의 질문/토론거리에 대한 답변은 본인이 댓글로 정리해서 남겨주시기 바랍니다.

**Comment by mycode01** [comment]
Q1. 5.8.3 리다이렉션(p.145) URL 서버증강이 뭘 의미하는가?

Q2. 프락시와 게이트웨이 둘다 약간 개념적으로는 교집합으로 묶이는 지점이 있다고 생각하는데, 이를 구체적으로 구분할 필요가 있나?
구분해야한다면 무엇을 기준으로 둘을 구분하는가?

Q3. 5.7.4 서버사이드 인클루드 ssi (p.142)를 잠깐 설명하였는데,
네이버에서는 대용량 트래픽처리를 위해 ssi를 사용한다고 하였다.(https://d2.naver.com/helloworld/6070967#ssi)
이를 구체적으로 어떻게 유용하게 활용할수 있을까?

**Comment by SeolYoungKim** [comment]
Q1. p136의 커넥션 다중화는 무얼 다중화 한다는걸까?

**Comment by jdalma** [comment]
- Q1. 136p에서 NIO가 한 개의 스레드로 소켓을 감지하여 다른 스레드에게 작업을 할당하는 걸로 아는데, 그럼 (c)에 해당하는 걸까?
  - (c)에 해당하는게 맞다면 BIO는 어디에 해당할까? (b)인가?

**Comment by Coen90** [comment]
Q1. 6.2 트랜스코더
- 프락시서버에서 클라이언트에 전달하기 전에 본문 포멧을 수정하는 장점이 무엇일까?
- 서버, 프락시, 클라이언트 어디서든 수정이 가능할 것으로 보이는데 프락시에서 변환하는 이유는 서버 부하를 줄이고 프락시-클라이언트 네트워크 비용을 줄일수 있기 때문인가?
- 프락시가 더 빠르기 때문인가?
- 혹은 다른 이유가 있는 것인가?
<br/>
Q2. 불법·유해 정보 사이트 차단도 프락시일까?
- 책의 어린이 필터의 예시처럼 ISP의 프락시가 응답을 차단하는 방식일까? 아니면 아예 다른 방식의 기술일까?
