### ISSUE TITLE
6주차: 7장 캐시 & 8장 통합점:게이트웨이, 터널, 릴레이

### ISSUE THREAD

**Issue by SeolYoungKim** [SeolYoungKim/http-definitive-guide-study#19]
## 7장 캐시 & 8장 통합점:게이트웨이, 터널, 릴레이
- 질문 혹은 토론거리를 댓글로 달아주세요.
- 하나의 댓글에 두 컨텐츠를 모두 넣어주세요.
- 자기 자신의 질문/토론거리에 대한 답변은 본인이 댓글로 정리해서 남겨주시기 바랍니다.

**Comment by jdalma** [comment]
- Q1. 191p 첫 번째 문단에서 "서버에게 보내는 GET 요청에 `If-Modified-Since` 헤더를 추가한다면 서버에서 일어날 수 있는 세 가지의 상황이 있다." 라는 말이 있는데,
  - ~~**재검사 적중**, **재검사 부적중**, **객체 삭제**를 판단하는 위치는 (WAS가 아닌)웹 서버일까?~~ **7.10에서 나옴**  
  - ~~그렇다면 웹 서버 설정을 통해 해당 헤더를 검증하는 기능을 키고 끌 수 있을까?~~
  - 그런 설정이 있다면 현업에서 컨트롤한 경험이 있으신지? 아니면 WAS에서 직접 캐시 헤더를 확인하며 개발한 경험이 있으신지? 
- Q2. 게이트웨이와 프록시, 터널 구분은 어떻게 해야하나??
  - 망에 포함되어있지 않으면 다 프록시라고 대충 생각했는데, 이번에 게이트웨이 읽다보니 망 내부에 포함안되는 것도 게이트웨이라고 했다.
  - 프로토콜이 변환되는 기준으로 보는 것 같은데.. 애플리케이션이 아닌데 프로토콜을 변환을 어떻게 시킬까 

> A1. 기본적으로 웹 서버의 기본 캐시 기능을 사용하면서 URL에 쓰레기 값을 붙이거나 문서를 갱신시키기 위한 고민은 하신 것 같다고 한다.
> A2. 부가기능의 차이와 외부 망과 내부 망을 잇는 것으로 구분할 수 있을 것 같다.  
> 단어 선택은 얘기 나누는 대상에 따라 다를 것이다.

**Comment by SeolYoungKim** [comment]
- Q1. p196에서, "프락시 연쇄가 길어질수록 각 중간 프락시는 현저한 성능 저하가 발생할 것"이라고 작성되어있다. 
  - 여기서 중간 프락시란 캐시 프락시 전부를 의미하는걸까? 
  - 중간 프락시만 성능 저하가 발생할까?
  - 연결이 지속되는게 아닐텐데 왜 성능 저하가 발생할까? keep-alive인 경우에만 성능 저하가 발생할까? 
    - 200p의 단계 6: 전송을 보면 "프락시 캐시는 클라이언트와의 커넥션을 유지할 필요가 있다"고 한다. 아마 커넥션을 유지하기 때문에 현저한 성능 저하가 발생하는 듯 하다.  
    - 그렇다면, 프락시 연쇄에서는 프락시 간 커넥션이 유지되는걸까? 

> A1) 100개의 요청이 있고, 제일 앞단이 10개의 캐시서버가 있다면, 뒷단으로 갈수록 캐시서버 숫자가 줄어들거에요. 그럼 캐시해결이 제일앞단에서 처리 안되면 뒤로 가겠죠. 캐시 적중이 떨어질수록 중간-후방에 있는 캐시 서버가 연결을 유지해야하므로 퍼포먼스가 떨어진다 이런 이야기로 보입니다.
> A2) 서울-부산이면 30ms 이면 간다. 대한민국 내에서 캐시 서버가 많이 필요하진 않을것. 게임의 경우는 대략 10ms 미만의 지연속도를 가질것임.

- Q2. p.243의 그림
  - ![image](https://user-images.githubusercontent.com/100072078/232305699-23337986-3ad1-411f-bff1-873bff482fea.png)
  - 위 그림에서, 클라이언트와 게이트웨이는 HTTP 통신을 하고, 게이트웨이와 `orders.joes...` 서버 간에는 SSL 커넥션이 맺어져있다. 
    - **A) HTTP 통신을 하지만 SSL 암호화가 되어있다.**
  - 알기로는, HTTPS는 SSL 위의 HTTP로써, SSL 커넥션을 통해 HTTP 통신을 하는 걸로 알고있는데, 이해한게 맞는지? 
  - 그렇다면 SSL 커넥션을 통해, 터널로 전달받은 HTTP 메세지가 그대로 전송되는걸로 이해하였는데, 이게 맞는지? 
    - **A) 게이트웨이가 인증을 하고 있다에 집중해야 함. 터널이 있든 없든, 인증을 받는 게이트웨이 일수도 있다. 이런 역할을 한다.에 집중** 
  - HTTPS 연결이 수립되기 위해서는 TLS 핸드셰이크 기작이 필요한것으로 알고 있다. 이는 클라이언트가 서버와 직접 맺는게 맞는지? 그림상의 d를 보면 443 포트로 TCP 커넥션을 맺는다고 되어있는데, 게이트웨이가 서버와 커넥션을 맺는건지? 
    - **A) 클라이언트 <-> 게이트웨이 <-> 서버, 즉 서버와 연결되는것은 게이트웨이다.**

**Comment by mycode01** [comment]
Q1. 7.12.3 로그 마이그레이션(p.225) 가 http랑 관련이 있나?
광고회사가 광고를 노출할때마다 정산이 얽히기 때문에 캐시한 로그를 주고 받아야한다는건 이해하겠으나,
한 섹션을 차지할정도로 중요한 이슈인지 모르겠다.

Q2. 캐시제어(cache-control) 응답 헤더의 값 중 must-revalidate가 선언이 필요한가?(p.211)
캐시가 만료되면 브라우저나 에이전트가 해당 캐시를 이용하기 위해서라면 재검사를 해야하는게 당연하게 생각 되는데, 이런 내용까지 선언이 필요할정도인지 모르겠다.
캐시 만료를 무시할정도로 멍청한 에이전트라면 cache-control 에 따른 정의도 무시할거같은데..

TMI1. 캐시 서버는 요청받은 컨텐츠가 캐싱 되어있는지 확인하기 위해서 1차로 메모리를 뒤지고, 2차로 디스크에 저장되어있는지 빠르게 확인하기 위해 블룸필터(bloom filter)라는 자료구조를 이용한다.(p.199) 물론, key-value store를 사용할수도 있다.
gpt 3.5에게 물어보면 블룸필터의 긍정오류/부정오류를 반대로 알려주기 때문에 주의하자. 블룸필터는 긍정오류가 발생할수있다.

TMI2. 로컬 저장장치와 네트워크 I/O버퍼의 데이터 전송을 피하기 위해 제로 카피(zero copy)라는 방법을 사용한다.(p.200)
이는 네트워크 전송을 위해 각 계층에 데이터를 복사하는게 아니라, 데이터의 주소를 전달하는 방식으로 리드 버퍼에서 곧바로 소켓 버퍼로 복사하는 방식을 사용하여 부하를 줄인다. 
sendfile()이라는 시스템콜(커널기능)을 이용하여 리드 버퍼 - 소켓 버퍼 - NIC 버퍼 복사가 이루어지며, 기존에 동작하던 방식인 리드 버퍼 - 어플리케이션 버퍼 - 소켓 버퍼 - NIC 버퍼 4단계에서 3단계로 줄었고, 
더욱 개선되어 리드 버퍼 - (디스크립터) - NIC 버퍼로 2단계가 되었다.(소켓 버퍼에 디스크립터가 추가되지만 실제 복사가 이루어지진 않음) 물론 커널버전과 하드웨어가 기능제공을 해야 가능하다. 
면접때 아파치 카프카를 물어본다면 필수로 물어볼 내용중 하나이다.

TMI3. 릴레이가 keep-alive 문제를 가지는 이유는 릴레이는 OSI 7계층중 3 ~ 4계층에서 동작하기 때문(p.244)
릴레이는 단순한 전달자이기 때문에 어플리케이션 레이어에 있는 데이터를 가지고 판단하지 않는다.
게이트웨이는 5 ~ 7계층에서 동작하기 때문에 이 두가지를 놓고 비교하는건 좀 이상한 비교이고,
최근에는 프록시나 게이트웨이가 구분이 모호한것처럼 릴레이도 굳이 구분해서 이야기하진 않는다.

**Comment by Coen90** [comment]
Q1.7.6.4 몇몇 네트워크 아키텍쳐는 단순한 캐시 계층 대신 복잡한 캐시망을 만든다. 
-  위와 같은 복잡한 동적 캐시망은 포털서비스와 같은 서비스 이외에서 사용하는 경우가 있는지 궁금합니다.
   - 글로벌적으로 보면 캐시망을 만드는 경우가 잘 없다(그만큼 큰 기업이 많지 않고, 필요한 경우에도 클라우드 내 iaas로 제공되는 서비스를 많이 사용한다고 함)

Q2. Expire, Cache-control: max-age를 변경하고싶을때 어떻게 할수있을까?  
- 7.10 캐시제어에서 Expire는 아파치 mod_expire 모듈을 통해 변경이 가능하다고 한다. 하지만 Expire는 depreciated 헤더(7.9.3)이기도 하며 ~~max-age변경에 대해서는 따로 언급이 없다.(이부분은 아파치 mod_header로 해결 가능해보이네요)~~   
- ~~서버에서 특정 모듈을 통해 변경이 가능한지,~~ 혹은 서버푸시를 통해 캐시컨트롤이 가능한지 궁금합니다.
  - 서버푸시가 일어나는 시점을 생각해보면 불가능해 보인다 함. 굳이 사용한다면 웹소켓를 사용하는게 적절해보임.(노가다김씨)
  - 구글에서는 삭제한다고 함

**Comment by 2jun0** [comment]
### Q1. [p237 8.5 터널] 어떻게 서버는 터널링을 알까?
-  포트가 닫혀있기 때문에 터널링을 통해 패킷을 전송한다고 했다.
-  서버가 터널링된 패킷? 트래픽? 메시지?를 어떻게 분석할지 여러 궁금증이 들었다.
-  서버는 어떻게 터널링 된 것을 알 수 있을까?
    -   80포트로 SSH 메시지를 보낸다고 했을때,
    -   80포트는 왠지 HTTP 메시지만 이해할 수 있을 것 같은데 약속된 프록시가 필요할까?
    -> 서버에서 다룰 수도 있겠지만~ 보통 게이트웨이를 둬서 변환을 해준다.
    -   다른 포트를 막으려고 방화벽을 만든 것인데 터널링으로 뚫어버리면... 보안은 괜찮은건가??
    -> 보안에 문제가 있을 수 있다.

### Q2. 여러 글로벌 서비스의 CDN의 신뢰도는 어디까지인가.
- 여러 글로벌 서비스는 일종의 캐시 프록시 서버인 CDN 서비스가 있어서 물리적 속도 제한에서 그나마 자유로운 것으로 알고 있다.
- 근데, 만약 태평양 해저 케이블이 불미스러운 일로 인해 끊기면 모든 서비스는 중지될까?
- HTTP 명세만 본다면, 신선도를 확인하고 난 뒤, 프록시 서버는 맛이 갈 것지만, 과연 그렇게 해 두었을까?
- 더 나아가서 점조직 형태의 레플리카 서버를 글로벌 하게 구축할 수 있을까?
-> a-z zone 을 봅시다. 이미 그렇게 많이 되어있음.
- chatgpt의 미래는 레플리카 서버일지도??
-> 미래에는 그럴지도 몰라~
- ~chatgpt에게 물어보고 싶은뎅 내가 쓰고 싶을때만 안된다.~

**Comment by rnhappysmile** [comment]
Q1. 7.11.1 나이와 신선도 수명만으로 캐시를 관리하는건 충분한가 ?
  - 네이버, 블로그등의 사이트에서 제공하는 배너 이미지 및 동영상은 충분히 커버가 가능 해 보인다.
  - 유튜브는 과연 가능 할 것인가 ? 물리적으로 CDN서버의 규모 확장을 하면 되겠지만 한계가 있다.
  - 지속적으로 캐시에 나이가 오래된 동영상을 지워야 할 것이다. 하지만 그 동영상이 현재도 많은 뷰 수를 가지는 영상이라면 ?

Q2. 7.2 대역폭 병목에 대해서 대응 할 방법은 ?
  - 대역폭 병목을 줄이기 위해서 우리는 캐시를 사용한다. 분산된 캐시 서버를 사용하고 있지만 한 곳으로 몰리게 된다면 어떻게 대응 할 수 있을까 ?
  - 리눅스에서 APT를 통해 다운로드 받을 때 설정이 잘못되어 있어 영국 서버에서 다운로드 받은 적이 있었다. 
  - 최근엔 카카오 데이터 센터가 화재로 인해서 apt 카카오 서버를 사용할 수 없었던 적이 있다. 이때 대응 방법은 ?

**Comment by hagyoung99** [comment]
- (200p) 캐시가 Date 헤더를 조정해서는 안된다는 것에 주의 하라. 라고 나와있는데 그러면 캐시를 가지고 date 헤더를 조정할 수 있는건가요? 가능하다면 Date 를 믿어도 되는건가요?

-  (208p) 강한 검사기는 콘텐츠가 바뀔 때 마다 바뀐다. 약한 검사기는 어느정도 콘텐츠 변경을 허용하지만, 콘텐츠의 중요한 의미가 변경되면 함께 변경된다.
  - 강한 검사기와 약한 검사기의 차이점은 이해했는데 좀 더 구체적인 변경 기준이 뭔지 궁금합니다.
