### ISSUE TITLE
7주차: 09장 웹 로봇 & 10장 HTTP/2.0 

### ISSUE THREAD

**Issue by SeolYoungKim** [SeolYoungKim/http-definitive-guide-study#20]
## 09장 웹 로봇 ~ 10장 HTTP/2.0 
- 질문 혹은 토론거리를 댓글로 달아주세요.
- 하나의 댓글에 두 컨텐츠를 모두 넣어주세요.
- 자기 자신의 질문/토론거리에 대한 답변은 본인이 댓글로 정리해서 남겨주시기 바랍니다.

**Comment by mycode01** [comment]
Q1. p.269 Disallow 지시자를 무시하는 봇에 대해서는 어떻게 대응해야하는가?
~~너가 뭘할수있는데? 컨텐츠 전송하는거 말고 뭘할수있냐고 ㅋㅋ~~
> 아이피 차단 말고는 현재 방법 없음 

Q2. 10.3.4(p.292) 프론트엔드 개발자가 웹페이지 개발시 서버 푸시에 대응해서 신경써야 하는 부분이 무엇인가?
예를들면 페이지에 포함될 js, css 파일을 서버푸시를 통해 서버가 클라이언트 요청 전에 먼저 전달을 해줄수 있다는것으로 이해가 되는데, 프론트엔드 개발자는 이것에 대응하여 개발을 해야하는지? 아니면 서버푸시는 브라우저가 뭔가 처리를 해줄수 있기 때문에 기존과 똑같이 개발하면 되는것인지?
> 서버푸시로 받은 데이터는 브라우저 캐시에 저장되기 때문에, 브라우저가 지원하지 못하면 얄짤없이 다시 요청을 할것이고,
> 브라우저가 지원한다면 서버푸시로 받은 데이터는 브라우저 캐시 스토리지에 저장되고, 해당 리소스를 요청할때 캐시를 먼저 참고하기 때문에 캐시 스토리지에 있는 리소스를 사용하게 된다.

**Comment by SeolYoungKim** [comment]
Q1. HTTP 1.1 -> HTTP 2.0으로 업그레이드 할 때 주의해야 할 점은 무엇이 있을까? 
- 두 버전 간의 차이점만 주의하면 되는걸까? 
- 버전을 업그레이드 할 때 요청 헤더에 HTTP2.0으로 버전을 바꿔주고, 차이점에 해당하는 부분만 2.0 버전에 맞게 바꿔주면 다 되는것일까? 만사 OK일까?? 
- 톰캣은 HTTP 1.1과 2.0을 알아서 구분해줄까? 는 설정 값을 따로 줘야하는 것 같음 -> 그렇다면 2.0으로 업그레이드 해줄 때, API들 전부 2.0설정값을 적용해줘야 할듯..? 

> - A1. 2.0으로 업그레이드 할 때 keep-alive 주의해야함. -> HTTP2.0이 되면서 keep-alive가 기본이 되면서 주의해야 할 부분이다. Port 고갈 날수도 있음. (요청이 많을때, 많은데 바로 끊고 재활용 안할때 주의)
> - A2. 서비스의 대상이 누군지에 따라, 브라우저의 환경을 고려해야 할수도 있다. 



Q2. HTTP 3.0의 시대(?)가 도래하지 않을까? [참고한 글](https://inpa.tistory.com/entry/WEB-%F0%9F%8C%90-HTTP-30-%ED%86%B5%EC%8B%A0-%EA%B8%B0%EC%88%A0-%EC%9D%B4%EC%A0%9C%EB%8A%94-%ED%99%95%EC%8B%A4%ED%9E%88-%EC%9D%B4%ED%95%B4%ED%95%98%EC%9E%90)
- HTTP 3.0은 UDP 기반인데, TCP는 사장되게 될까? 
- 하지만, TCP는 신뢰할 수 있는 프로토콜이다. 아예 사장되진 않을것 같다. 만약 순서가 정말정말정말 중요한 서버가 있다면, TCP는 계속 사용될 것 같다. 이는 HTTP 3.0 위에서도 잘 동작하게 해놨겠지..? 구글에서 QUIC 프로토콜로 구현을 해둔 것 같던데, 이를 주로 사용하게 될까? (아래 사진 참고)
<img width="973" alt="image" src="https://user-images.githubusercontent.com/100072078/233822964-b05ae870-2ffc-4ee3-96c1-3debd9f7bc49.png">

- 내가 놓친게 있는데, UDP는 "하얀 도화지"이다. 즉, 내가 그림을 그리는 대로 동작한다는 것. 순서를 보장하게 할 수도 있다. 그렇다면 UDP는 순서를 어떻게 보장하게 할 수 있을까 

> - A1. 영상 스트리밍 환경에 유용할것. 패킷이 약간 유실되더라도 괜찮은 부분에 사용될것임. (화면을 빨리 보여주는게 더 우선순위가 높을 때)

**Comment by jdalma** [comment]
Q1. HTTP/2.0 프레임의 종류가 있던데, 프레임을 어떻게 지정해줄 수 있을까? 
  - 개발자가 애플리케이션 레벨에서 직접 컨트롤 할 수 있을까?
  - 구현체마다 다르겠지?

> A. 프레임을 직접 수정할 일은 없을 것이다.  
> 클라이언트와 서버에서 자체적으로 적용되고 있을 것이다.

Q2. 10장 HTTP/2.0 읽고나서 느낀점이 HTTP/1.1보다는 커넥션이 길게 유지되며, 웹 소켓? 같은 느낌인데 이해가 잘 안간다.
  - 다들 어떤 식으로 이해했는지 궁금하다.

> A. 결국 웹 트랜잭션은 HTTP/1.1과 동일하지만 그 사이에 일어나는 데이터 교류 흐름이 조금 더 유연해진 것이다.

**Comment by 2jun0** [comment]
## 1. 악의적인 크롤러를 잡는 방법
약속을 어기는 못된 크롤러를 잡기위한 함정을 만들 수 있는데, 아래 글에 재미있는 방법이 있어 공유합니다.
정리를 좀 해봤는데 정확하지 않을 수 있으니 아래 글도 한번씩 봐주세용
https://fleiner.com/bots/

- **숨겨진 리소스를 보기 위해 robots.txt의 항목을 마구 사용하는 로봇 (Disallow까지도)**
   웹사이트 내에서 접근할 수 없는 특수 링크를 가리키는 항목을 추가한다. (Disallow로)

- **cgi 스크립트를 통해 링크를 따라가는 로봇**
   로그 파일로 확인할 수 있답니다.

- **모든 웹 사이트를 몇초 만에 방문함**
   무슨말인지 모르겠음. 아마 빠르게 크롤링 하는 걸 말하는 듯.
   이것도 로그로..

- **웹 사이트를 너무 자주 방문하는 로봇**
   일주일에 한번 이상이라고 되어있는데 이건 진짜 너무하고 길어봐야 1시간에 몇번 아닐까
   이것도 로그로 한다고함

- **이메일 주소를 수집하는 로봇**
   트랩 이메일 주소를 숨어둬서 트랩 이메일이 주소를 받았는지 확인
   누가 이 트랩 이메일을 봤는지 로그에서 찾아서 식별하면 된다고 함

## 2.Q DDos와 http2
http2가 http1보다 더 빠르고 많은 요청/응답을 교환할 수 있는 걸로 알고있는데
단순히 생각해서 이렇게 하면 더 DDos 공격에 취약한것 아닌가? 하는 생각이 들었다.
분명 http2를 만들때 이런 점을 생각했을텐데 어떻게 준비해야 할까?
> 커넥션 맺는 비용이 크니 오히려 http2가 더 강건할듯.

**Comment by rnhappysmile** [comment]
Q1. 크롬에서 HTTP/2 서버 푸시가 제거 된 이유는 무엇인가?
  - 1.25%만이 기능을 사용하고 있다.
  - HTTP/2 서버 푸시 사용에 대한 분석 결과는 명확한 성능 상향 없이 저하도 나타난다
  - 1.25% -> 0.7%로 줄어든 지원률
  - 서버 푸시 대안은 있는가 ? 103 Early Hints를 통해 크롬에서만 지원 중
  
<img width="537" alt="image" src="https://user-images.githubusercontent.com/20284918/233967359-91e5be99-0f81-4d2a-a13c-6a957790e2c5.png">

![image](https://user-images.githubusercontent.com/20284918/233967499-afefe377-1602-4edf-a3ab-0875368f8f68.png)


Q2. HTTP/1.1 파이프라인의 HoL 블로킹(Head of Lock Blocking) 현상을 HTTP/2의 멀티플렉싱은 스트림을 어떻게 활용하여 해결 하였는가 ?

**Comment by Coen90** [comment]
Q1. robot.txt의 Disallow 
META tag를 무시하고 크롤링을 할 경우 법적 재제를 가할 수 있는가?
영업비밀이나 부가가치를 가진 정보들 등에 대해 크롤링을 하는 경우 법적으로 조치를 취하는 경우는 뉴스로 보았지만, 로봇에 명시한것 만으로 가능할까  
- (야놀자vs여기어때)형사는 서버를 열어놨으니 무단침입이 아니다.
- (야놀자vs여기어때)민사상 손해배상은 해라
- robots.txt 만으로는 소송이 어려울것 같다.

Q2. 10.3.3 헤더압축에서 보면 헤더를 압축하여 '헤더 블록 조각'들로 쪼개져서 전송된다고 한다.  
불법·유해 정보 사이트 차단은 SNI로 패킷을 분석해 차단하는 하는데, 이를 피하는 방법으로 sni 파편화하여 mtu를 쪼개서 보내는 방법이 있다고 한다.  
그렇다면 http 2.0을 사용하는 사이트는 우회도 필요없이 모두 접근이 가능한 것일까?
- 모르겠다. 하지만 P***Hub는 http2.0 사용중이다..
