### ISSUE TITLE
8주차: 11장 클라이언트 식별과 쿠키, 12장 기본 인증, 13장 다이제스트 인증

### ISSUE THREAD

**Issue by SeolYoungKim** [SeolYoungKim/http-definitive-guide-study#21]
## 11장 클라이언트 식별과 쿠키, 12장 기본 인증, 13장 다이제스트 인증
- 질문 혹은 토론거리를 댓글로 달아주세요.
- 하나의 댓글에 두 컨텐츠를 모두 넣어주세요.
- 자기 자신의 질문/토론거리에 대한 답변은 본인이 댓글로 정리해서 남겨주시기 바랍니다.

**Comment by SeolYoungKim** [comment]
Q1. p318에서 발췌 
```text
보수적인 캐시는 Cookie 헤더가 포함된 요청에 응답으로 오는 문서는 캐시하지 않을 것이다. 

Set-Cookie가 있는 이미지에 대해서는 캐시를 하지 않지만,
Set-Cookie가 있는 텍스트는 캐시를 하지 않는 캐시도 있다. 

더 효율적인 방식은 캐시 이미지에 파기 시간이 0인 Cookie 헤더를 설정해서 매번 재검사를 하도록 강제하는 것이다.
```
- 여기서, Set-Cookie가 있는 이미지에 대해서는 캐시를 하지 않는다 -> 이미지가 무엇을 의미하는 것인지 궁금합니다
  - A: 이미지 -> 어떠한 컨텐츠를 의미하는 것 같음 
- Set-Cookie가 있는 텍스트는 캐시를 하지 않는 -> 텍스트라 함은 본문 내용일까요? 
  - A: 텍스트 -> 어떠한 컨텐츠를 의미하는 것 같음   
- 파기시간이 0인 Cookie와 재검사는 어떠한 연관이 있나요? 파기시간에 상관 없이 Cookie가 있다면 검사를 해야하는게 아닌가요? 책이 말하고자 하는 의도를 파악하지 못했습니다.
  - A: 캐시할 어떠한 컨텐츠에 대한 파기시간이다. 쿠키를 검사하는 게 아니다. 

> A: 같은 요청이어도 다른 내용을 보여줘야하면, 캐시를 하지 말아라! (개인화, 인증 관련)

Q2. JWT에 대해 
- JWT도 안전하다고 생각하시는지? 
- JWT가 나오게 된 이유는 무엇일까?
- JWT와, 암호화된 String은 무슨 차이가 있을까? String을 비슷한 방식으로 암호화 한다면, 똑같지 않나? (면접 때 받았던 질문. 대답못함^^;)

**Comment by jdalma** [comment]
- 설영님 1번 질문 관련 : 보수적인 캐시라는 의미는 뭘까?
  - `.... 하지 않는 캐시도 있다`라는 문장이 이해가 안간다. 캐시 설정 정보에 따른 경우를 의미하는건지?
- Q1. 323p **12.1.2 인증 프로토콜과 헤더**에서 서버가 401응답을 내리면 WWW-Authenticate헤더를 자동으로 정의 되는 것 처럼 말하는데 스프링에서는 401을 내려도 헤더가 정의되지는 않음
  - RFC2616에서는 `요청에 사용자 인증이 필요합니다. 응답에는 요청된 리소스에 적용 가능한 챌린지를 포함하는 WWW-Authenticate 헤더 필드(섹션 14.47)가 포함되어야 합니다.` 포함되어야 한다고 나와있음
  - 클라이언트가 `Authorization`헤더에 사용자 정보를 담아서 요청한다면 서버에서도 `Authorization`헤더에서 값을 직접 꺼내줘야되는걸까?
- Q2. 현업에서 JWT, 세션 관리 방식 중에 어떤 방식을 사용하는지? 저는 혼용해서 사용 중 (왜 혼용하는지는 모르겠음. 레거시는 레디스에 스프링 세션 ID 넣어서 쓰고, 신규 개발은 JWT를 사용하는 듯)
  - 세션 데이터를 서버가 저장하면 사용자가 많아질수록 메모리를 차지하기 때문에, 그 부담을 클라이언트에게 넘기기 위해 JWT를 사용하는 이유도 있다고 생각함. 그 의미로 제 회사에서는 사용자가 많지 않아 JWT를 사용하는 의미가 커보이지 않음
  - 세션이 안전한지, JWT가 안전한지는 결국 SSL 통신 덕분에 안전한 것 아닌가 싶다.

**Comment by mycode01** [comment]
Q1. digest 인증 알고리즘 설명(p.340)에 갑자기 nc라는 값이 등장하는데, 이게 뭐지?
> nonce counter, nonce를 몇번 사용했는지 감지하여 정상적인 요청인지를 확인할수있다.


Q2. 요즘은 쿠키의 사용이 '위험하다'라고 주입식 처럼 교육되고 있는 모양인데, 그 근거는 무엇인가? 
jwt로 대체되면 안 위험한가?
> 생각없이 사용하는 쿠키가 위험하지, 같은 방식으로 생각없이 사용한다면 조작의 위험은 없지만 정보노출에 있어서는 jwt도 똑같이 위험함.

TMI1. base64encode와 base64urlencode는 살짝 다름.
TMI2. 중간자 공격에는 ssl할애비가 와도 안전하지 않음.

**Comment by Coen90** [comment]
Q1. 13.1.3 재전송 방지를 위한 난스 사용.
재전송 방지를 위하여 비밀번호에 난스를 섞어 매번 다른 해시를 받아내는 기술이라고 한다. csrf와 비슷하다는 생각이 드는데 왜 요즘은 사용하지 않을까?
- csrf도, 난스도 요즘 잘 사용하지 않는다.
- 난스, csrf 둘 다 어딘가에 검증을 위한 정보를 저장해야 하기 때문이다.

Q2. JWT관련.
jwt 토큰은 주로 localstorage에 저장하거나 cookie로 저장하는 방법 두가지로 쓰인다고 알고있다.(실무에서 아직 사용 안해봤음) 경험상 어떠한 방법이 가장 안전하다고 생각하는지 궁금합니다.
- 취향차이같다. 
- 로컬스토리지, 쿠키 둘 다 장단점이 있다.
- 로컬스토리지 -> 화면을 꺼도 로그인 정보를 남겨두기 위해 사용했던 경험을 본 적이 있다.(스마일님)

**Comment by 2jun0** [comment]
### TMI1. Refresh Token 탈취를 방지하기 위한 더 좋은 방법은 없을까? -> RTR(리프레시 토큰 로테이션)
"Remember Me" 같은 기능을 사용한다면, 세션(access token)이 만료되기 전에 Refresh Token을 인증 서버로 전송하여 재인증을 시도한다.
Refresh Token도 만료기간이 있지만, 그전에 탈취당해서 나도 모르게 해커가 맘대로 인증한다면?

이 문제를 해결하기 위해 RTR(Refresh Token Rotation)이라는 기능이 있다.
인증을 해서 Access Token을 받을 때마다 Refresh Toekn를 갱신하는 원리.
![image](https://user-images.githubusercontent.com/7973448/235437341-cff4747c-ba8d-4635-b3b7-5693bfceab83.png)

공격자가 내 리프레시 토큰을 사용하면 중복사용되어 탈취 여부를 알게 된다.
![image](https://user-images.githubusercontent.com/7973448/235437403-1eec4087-83e0-4046-8ade-587bab758e2f.png)

https://pragmaticwebsecurity.com/articles/oauthoidc/refresh-token-protection-implications.html
### Q1. 크롬의 비밀번호 수집. 안전할까?
이건 기술적인 것은 아니지만, 여러분들의 의견이 궁금해서 올려봅니다.
브라우저가 자동완성 기능을 제공하려고 비밀번호를 저장하곤 합니다.

요즘엔 기기간 동기화도 되는것 같던데 제 비밀번호가 점점 public이 되어가는 느낌이 듭니다.
설령 절대 스크립트로 브라우저의 비밀번호를 탈취하지 못한다고 해도, 외부 악성 프로그램이 접근해서 탈취할 수도 있지 않을까요?

여러분들의 의견이 궁금합니다..
![스크린샷 2023-05-01 오후 6 54 44](https://user-images.githubusercontent.com/7973448/235454615-12fdfb22-ea16-41b8-a200-79b5443b73ea.png)
> 구글이니까 일단 안심이지만, 위험할 수 있다. ㅠㅠ 
> 그리고 바이러스에 의한 해킹은 도저히 막을수가 없다.

### Q2. Location 헤더 없이 302 Found 보내기?
p317 (ebook p346)의 그림 11-5의 (d)를 보시면  Location헤더가 없습니다.
제 생각에는 책이 잘못된 것 같은데 잘못된게 맞을까요?
> 책이 잘못되었다기보다 요약인것 같다 ㅎㅎ

**Comment by rnhappysmile** [comment]
Q1. 다이제스트 인증은 보안되지 않은 것으로 간주되므로 최신 응용프로그램에서는 사용하지 마십시오. 가장 분명한 문제는 암호를 일반 텍스트나 암호화 또는 MD5 형식으로 저장해야 한다는 것입니다. 이러한 스토리지 형식은 모두 안전하지 않은 것으로 간주됩니다. 여기서 암호화 또는 MD5 형식으로 스토리지 하는게 안전하지 않은 이유는 무엇인가요 ?
출처 : https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/digest.html

Q2. 13.5.2 재전송 공격에 대해 어떤 방법으로 방어를 하시나요 ?

혹시.. 사이트 보안 인증서에 대해서 간략하게 소개 해주실 수 있나요 ?
