### ISSUE TITLE
9주차: 14장 보안 HTTP & 15장 엔터티와 인코딩 

### ISSUE THREAD

**Issue by SeolYoungKim** [SeolYoungKim/http-definitive-guide-study#22]
## 14장 보안 HTTP & 15장 엔터티와 인코딩 
- 질문 혹은 토론거리를 댓글로 달아주세요.
- 하나의 댓글에 두 컨텐츠를 모두 넣어주세요.
- 자기 자신의 질문/토론거리에 대한 답변은 본인이 댓글로 정리해서 남겨주시기 바랍니다.

**Comment by mycode01** [comment]
Q1. SSL, TLS는 OSI 7 레이어 모델의 어느 계층에 속하는가?
p.373 의 그림 14-13에서는 SSL, TLS는 어플리케이션, 트랜스포트 레이어 사이 보안 계층이라고 한다.
하지만 OSI 7 레이어 모델에서는 보안 계층이라는 레이어는 별도로 없고, 둘 사이에는 프리젠테이션 레이어와 세션 레이어가 존재한다.(TCP/IP 모델은 애초에 어플리케이션 레이어로 퉁침)
검색해보니 프리젠테이션 레이어에 편입시킨 자료도 있고, gpt는 어플리케이션 혹은 전송 계층이라고 한다.
본인이 생각하기에 HTTP위에서 암호화 되어 전송되기 때문에 어플리케이션 레이어라고 생각하는데 다른 분들의 의견은 어떤지 궁금하다.

Q2. 15.4.3 multipart form(p.403)에 대해 설명하는데, 파일 업로드 구현시 멀티파트를 이용하여 제목, 설명 등의 메타데이터와 함께 파일을 업로드하는것이 최선이라고 생각하지 않는다.
최선이라 생각하는 http 프로토콜에서의 파일 업로드 방식을 이야기해봅시다.

**Comment by SeolYoungKim** [comment]
Q1. p367 (14.5.1 서명은 암호 체크섬이다) 발췌
```text
서명은 메시지 위조를 방지한다. 만약 악의적인 공격자가 송신 중인 메시지를 수정했다면, 체크섬은 더이상 그 메시지와 맞지 않게 될 것이다. 

- 이하 생략 -
```
- 서명을 한 후의 메시지 위조가 불가능하다면, 서명을 하기 전에 메시지를 탈취해서 위조를 하는 것은 가능할까?
  - 예를 들어, "abc"라는 메시지가 서명 전에 "babo"로 변경되었고, 그걸 서명을 한다면? 논리적으로 이게 되긴 하려나 싶긴한데...  
  - 공격자는 서명 후 송신되는 메세지만을 탈취할 수 있을까? 아니면 서명 전의 메세지도 바꿔치기 할 수 있을까? 
  - 해킹은 어느 수준까지 가능한걸까? 

> A. 가능은하다. 다만 비효율적일 뿐. 해커가 우리껄 굳이? 

Q2. p399 (15.2.5 엔터티 본문 길이 판별을 위한 규칙) 
- 해당 내용에 명시된 규칙들을, 보통 개발자들은 신경쓰지 않고 구현하는 것 같다. 이는 톰캣은 기본적으로 구현하고 있기 때문일까? 
- 톰캣은 HTTP 명세를 어디까지, 어느정도 수준으로 구현 해두었을까? 

> A. 톰캣은 아마 HTTP 명세를 대부분 추상화 해두었을 것이다. 명세가 업데이트 될 때마다 이는 반영이 될 것이라고 생각한다.

**Comment by hagyoung99** [comment]
Q1. [알라딘 400p/책371p] 브라우저가 인증서를 받으면 서명기관을 검사하는데, 서명기관의 인증서가 미리 설치되어있다면 검증되지만 서명기관이 모르는 곳이라면 사용자에게 대화상자를 보여준다고 책에 나와있는데 그럼 서명 기관의 인증서 관리를 구글에서 하고있는 걸까요? 관리한다면 어떤 기준으로 신뢰할 수 있다고 판단할까요

Q2. [알라딘 450p/책 421p] 델타 인코딩은 변경된 부분을 찾고, 어떻게 적용할지를 클라이언트와 맞춰서 오래된 버전에 델타를 적용해 새로운 버전의 페이지를 만드는것이다 라고 이해했습니다.
 델타 인코딩을 하는 목적이 전체 페이지를 받아오는것보다 부분을 찾아서 적용하는게 빨라서인거같은데 요청에 대해 차이점을 찾고, 그부분만을 다시 로딩해서 하는게 더 빠를 수 있나요?
현재에는 사용하지 않는거같은데 그럼 지금은 부분적으로 가져오기 위해 뭘 사용하나요?

**Comment by 2jun0** [comment]
### Q1 -> A1. RSA 암호화에서 소수는 어떤 수를 정할까?
그냥 간단한 소수 3, 5는 엄청 위험할 것 같다.
그렇다면 자주 쓰는 소수 set이 있을 것 같은데 그게 뭘까?

ChatGPT는 아래와 같이 설명해줬다.
> RSA 알고리즘에서는 보통 매우 큰 소수(p, q)를 사용합니다. 이러한 소수는 보안성을 강화하기 위해 무작위로 선택됩니다.
>
>보통 소수의 크기는 비교적 큰 수로 선택됩니다. 일반적으로 1024비트에서 4096비트 사이의 소수를 사용합니다. 더 큰 소수를 사용할수록 암호화의 안전성은 증가하지만 계산 비용이 높아지게 됩니다.
>
>따라서 RSA 알고리즘에서 사용되는 소수는 임의로 선택되며, 그 크기는 암호화의 안전성과 계산 비용 사이의 균형을 고려하여 결정됩니다.

이미 전에 생각했었네.. 하핫핫
https://2jun0.tistory.com/20

~소수 관련 재밌는 문제: https://www.acmicpc.net/problem/27907~

### Q2 Transfer-Encoding은 http2에서 쓸 수 없다던데 왜지?
Transfer-Encoding에 대해 이해가 잘 안되서 정보를 찾아보던 중... http2에서는 이 헤더를 사용할 수 없다고 한다.
왜 추가할 수 없는 걸까요?
그렇다면 http2에서 청크 형식으로 보내고 싶다면 어떻게 할까요?

### Q3 DES 알고리즘을 이용한 암호화?
p.363을 보면 비트 수를 늘리면 DES 알고리즘도 충분히 안전하다는 것 같다.
근데 AES나 RSA는 봤어도 DES는 실제로 별로 못본것 같다.
DES는 안전하지 않나?

### Q4 지속연결과 전송 인코딩
p.411을 보면 전송 인코딩을 사용하면, 크기가 0인 청크로 본문이 끝났음을 알리고 커넥션을 열린채로 유지한다고 하는데, 그러면 커넥션을 어떻게 해야 끊을 수 있는걸까?

**Comment by rnhappysmile** [comment]
Q1. 14.4.2 혼성 암호 체계와 세션 키, 실제로 현업에서도 대칭키와 비대칭키를 혼합해서 많이 사용하나요 ? 

Q2. 15.3 엔티티 요약, 트랜스코딩 프락시란 무엇인가 ?
15.5.1 콘텐츠 인코딩 과정, 다운스트림 프락시란 무엇인가 ?
