### ISSUE TITLE
10주차: 17.5장 트랜스코딩 & 18장 웹 호스팅 & 20장 리다이렉션과 부하 균형 

### ISSUE THREAD

**Issue by SeolYoungKim** [SeolYoungKim/http-definitive-guide-study#23]
## 17.5장 트랜스코딩 & 18장 웹 호스팅 & 20장 리다이렉션과 부하 균형 
- 질문 혹은 토론거리를 댓글로 달아주세요.
- 하나의 댓글에 두 컨텐츠를 모두 넣어주세요.
- 자기 자신의 질문/토론거리에 대한 답변은 본인이 댓글로 정리해서 남겨주시기 바랍니다.

**Comment by SeolYoungKim** [comment]
Q1. 트랜스 코딩을 해주는 프락시 or 서버를 구성해보신 경험이 있는지? 
- 있다면, 어떤 방식으로 구현해야 할까요? 
- 보통 광고같은 것은 구글이나 네이버 이런 기업들이 제공하는 코드를 html 파일에 삽입하는 방식으로 구성될 것 같은데, 이런게 트랜스 코딩에 해당하나요?

**Comment by mycode01** [comment]
Q1. 489쪽 18.4 웹 사이트 빠르게 만들기 라는 단락에서 트래픽을 분산시키고, 컨텐츠를 사용자에게 물리적으로 가깝게 위치시키고, 전송시 압축을 하는 방식을 이야기하고 있는데,
자신의 서비스가 너무 느려 위와 같은 방법이나 꼼수를 사용해 속도 혹은 사용자 경험을 좋은방향으로 늘렸던 경험을 이야기해봅시다.
설명하기도 힘들고 알아듣기도 힘드므로 국소적인 수정보다는 책에서 설명한 방식에서처럼 인프라 구성이나 네트워크, 추상적인 프로그램의 흐름을 위주로 이야기해봅시다.

**Comment by 2jun0** [comment]
### Q1. p536, 2번째 단락이 좀 이해가 안됩니다.
> 만약 출발지 아이피 주소가 그 클라이언트의 아이피 주소로 계속 남아있다면, (하드웨어의 관점에서) 서버에서 클라이언트로 바로 가는(스위치를 거치지 않고) 경로가 존재하지 않아야 한다.

오히려 아이피 주소가 스위치의 것이 아닌 클라이언트의 것이면, 서버에서 클라이언트로 바로 가는 경로가 있어야 하지 않나요????? (뭐지?)

**Comment by rnhappysmile** [comment]
Q1. 트랜스코딩은 어떻게 사용 할 수 있는가 ? 
서버가 클라이언트의 요구에 맞는 문서를 아예 가지고 있지 않을때, 서버는 기존의 문서를 클라이언트가 사용할 수 있는 무언가로 변환하는 것을 트랜스 코딩이라고 한다.
[LINE 트랜스코딩 서버 아키텍처 개선기 - 1](https://engineering.linecorp.com/ko/blog/line-transcoding-server-architecture-improvement-1) (앞부분 들어가며 부분만 읽으셔도 됩니다)

Q1. 책에서 나온 리다이렉션은 AWS를 사용할 경우 고려 할 대상인가요 ? 신경 쓰지 않아도 되는 부분인가요 ? 제가 이해하고 있는 리다이렉션은 주문후 주문 결과화면을 처리 하는걸로 이해하고 있었습니다. (새로고침 시 결과 화면이 조회 될 수 있도록)
