### ISSUE TITLE
학습 하면서 찾은 좋은 글 (feat. 1주차 내용 정리)

### ISSUE THREAD

**Issue by SeolYoungKim** [SeolYoungKim/http-definitive-guide-study#7]
# 댓글 남기는 방법

```text
### 해당 글의 내용
링크 
```

<br/>
<br/>

# 1주차 내용 정리 
- telnet 
  - 애플리케이션 계층에서 동작
  - tcp/ip 사용 
  - ssh로 대체 
  - 접속 여부만 알기 위해서는 `ping`을 사용해도 됨 

- tunnel
  - 터널의 시작과 끝에 벽이 있다고 가정 -> 벽에 구멍이 있는데 구멍이 80포트임 -> 원하는 애플리케이션과의 통신을 위해 80포트를 빌리는 행위 
  - 통신을 주고받는 "통로"

- url 인코딩 
  - URL 인코딩은 URL에서 사용되는 일부 문자들을 다른 문자로 변환하는 과정입니다. 이것은 URL에서 사용될 수 없는 문자들을 안전하게 전송할 수 있도록 해 줍니다.
  - URL은 ASCII 문자 집합을 사용합니다. 따라서, ASCII 문자 집합에 포함되지 않는 문자, 예를 들어 공백, 한글, 일본어, 중국어 등의 문자는 URL에서 인코딩되어 전송되어야 합니다.
  - URL 인코딩은 "%" 문자와 이에 이어지는 두 개의 16진수 숫자로 표현됩니다. 예를 들어, "한글"은 "%ED%95%9C%EA%B8%80"으로 인코딩됩니다. 이렇게 인코딩된 URL은 모든 브라우저나 서버에서 이해할 수 있는 형태로 전송될 수 있습니다.
  - URL 인코딩은 보안과 관련하여도 중요합니다. URL 인코딩을 사용하지 않으면, 악의적인 사용자가 URL을 변조하여 공격할 수 있는 보안 취약점이 발생할 수 있습니다. 따라서, URL 인코딩은 안전하고 정확한 데이터 전송을 위해 중요한 역할을 합니다.

**Comment by SeolYoungKim** [comment]
# HTTP 1.0과 2.0의 차이 
https://jaehoney.tistory.com/281

**Comment by jdalma** [comment]
[`RFC5681` TCP Connection 느린시작](https://www.rfc-editor.org/rfc/rfc5681.html#section-3.1)

**Comment by mycode01** [comment]
https://yozm.wishket.com/magazine/detail/1956/
저번에 이어 또 올라온 글인데 내용도 그때랑 비슷합니다.

**Comment by SeolYoungKim** [comment]
[grpc](https://chacha95.github.io/2020-06-15-gRPC1/)
